// ui-react/src/Secured.tsx
import { userManager } from '@/auth';
import axios from 'axios';
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

function Secured() {
  const [data, setData] = useState({});

  const getData = async () => {
    const user = await userManager.getUser();
    const { data } = await axios.get('/api/secured', {
      headers: {
        Authorization: `Bearer ${user?.access_token}`,
      },
    });
    setData(data);
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <div>
      <p>Message from secured resource : {JSON.stringify(data)}</p>
      <div>
        <Link to="/">
          <button type="button">Back</button>
        </Link>
      </div>
    </div>
  );
}

export default Secured;

// ui-vue/src/components/Secured.vue
<template>
  <div>
    <p>Message from secured resource : {{ data }}</p>
  </div>
  <div>
    <button @click="back">Back</button>
  </div>
</template>

<script>
import { defineComponent } from '@vue/runtime-core';
import router from '@/routes';
import axios from 'axios';
import userManager from '@/auth';

export default defineComponent({
  setup: async () => {
    const user = await userManager.getUser();
    const { data } = await axios.get('/api/secured', {
      headers: {
        Authorization: `Bearer ${user.access_token}`,
      },
    });

    const back = () => {
      router.push('/');
    };
    return { back, data };
  },
});
</script>

<style></style>
